spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cartify
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: cartify_redis
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: your.email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: 5b7e06892ace6899d76949f2b9045c32d48d7a041c2be979d3057b6b0836e779
  expirationMs: 3600000

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}


logging:
  level:
    org.springframework.security: DEBUG