spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080