services:
  postgres:
    image: postgres:15-alpine
    container_name: cartify_postgres
    environment:
      POSTGRES_DB: cartify
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - cartify-net
  
  cartify:
    build: ../
    container_name: cartify_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - cartify-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cartify
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  redis:
    image: redis:alpine
    container_name: cartify_redis
    ports:
      - "6379:6379"
    networks:
      - cartify-net

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: cartify_zookeeper
    ports:
      - "2181:2181"
    networks:
      - cartify-net

  kafka:
    image: wurstmeister/kafka
    container_name: cartify_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - cartify-net

networks:
  cartify-net: